/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_crail_jni_CrailJNIBridge */

#ifndef _Included_com_example_crail_jni_CrailJNIBridge
#define _Included_com_example_crail_jni_CrailJNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_crail_jni_CrailJNIBridge
 * Method:    initializeJNI
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_crail_jni_CrailJNIBridge_initializeJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_example_crail_jni_CrailJNIBridge
 * Method:    finalizeJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_crail_jni_CrailJNIBridge_finalizeJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
